
meta_product_name: "Coin Squirrel"
meta_title: "Coin Squirrel - Earn in-game rewards for your favorite game by shopping online"
meta_description: "Probably the best way to get ingame Items for free! Start collecting now and enhance your game experience!"
meta_image: "https://res.cloudinary.com/dmr1qubzk/image/upload/v1552567822/Screenshot_2019-03-14_at_13.44.41.png" # should exist in `app/assets/images/`
